---
apiVersion: v1
kind: Service
metadata:
  name: preprocessingservice
  labels:
    app: preprocessingservice
spec:
  type: NodePort
  selector:
    app: preprocessingservice
  ports:
  - protocol: TCP
    port: 8080
    name: http
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pricingservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: preprocessingservice
    spec:
      containers:
      - name: shopfront
        image: chatbot-acrhub-int.chinaeast.cloudapp.chinacloudapi.cn:5000/preprocessingservice
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1